#!/usr/bin/env bash
set -euo pipefail
cd "/huyang2/double-loop/.worktrees/rwkv-maskcliff-83ccd29-20260630T1231Z"
export CUDA_VISIBLE_DEVICES=0
export SMOKE_DONE=1
export SKIP_SETUP=1
export SOURCE_SNAPSHOT_MODE=lean
export UPDATE_LEADERBOARD=0
export XDG_CACHE_HOME=/huyang2/double-loop/.cache
export PIP_CACHE_DIR=/huyang2/double-loop/.cache/pip
export HF_HOME=/huyang2/double-loop/.cache/huggingface
export TORCH_HOME=/huyang2/double-loop/.cache/torch
export TORCH_EXTENSIONS_DIR=/huyang2/double-loop/.cache/torch_extensions
export PATH=/huyang2/double-loop/.cache/bin:$PATH
export PYTHON_BIN=/opt/conda/bin/python
export OFFICIAL_SUDOKU_DATA_DIR=/huyang2/double-loop/official_eqr_sudoku_repro_20260623/data/sudoku-extreme-1k-aug-1000
export SUDOKU_SIZE=9
export BACKBONE=rwkv
export RWKV_KERNEL=statepassing
export D_MODEL=256
export LAYERS=12
export HEADS=16
export HEAD_DIM=16
export CHANNEL_MULT=4
export L_CYCLES=2
export MAX_LOOPS=8
export FULL_STEPS=2000
export FULL_BATCH=96
export FULL_EVAL_N=512
export HOLES_MIN=46
export HOLES_MAX=64
export EVAL_HOLES=56
export EVAL_HOLES_LIST=56
export OFFICIAL_EVAL_BLANK_RANGES=46-50,51-55,56-64
export EVAL_CHECKPOINT_STEPS=500,1000,1500,2000
export SAVE_TRAIN_CHECKPOINT_EVERY=500
export TRAIN_CHECKPOINT_DIR=/huyang2/double-loop/models/rwkv-official-maskcliff-d256l12-s2000-20260630T1240Z-83ccd29
export FULL_ROLLOUT_KS=
export ROLLOUT_LOOP_VALUES=
export FULL_LOG_EVERY=100
export BLANK_LOSS_WEIGHT=8
export FORWARD_DTYPE=bfloat16
export FUTURE_SEED_SCALE=1
export CASE_BANK_N=2
export CASE_BANK_EVAL_N=256
export CASE_BANK_LOOP_VALUES=1,2,3,5,8
export RUN_NAME=rwkv-official-maskcliff-d256l12-s2000-20260630T1240Z-83ccd29
./run.sh full
